<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
   xmlns:tns="http://hello.org/wsdl"
   xmlns:ns="http://hello.org/types"
   targetNamespace="http://hello.org/wsdl">
  <types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://hello.org/types">
    </schema>
  </types>
  <message name="messageName"/>
  <portType name="typeName"/>
  <binding name="bindingName" type="ns:typeName"/>
  <service name="serviceName"/>
</definitions>